name: CI Testing
on:
  push:
    branches:
      - "homework31"
  pull_request:
    types: ['opened', 'synchronize']
jobs:
  lint-playwright: 
    name: 'Lint Playwright tests folder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  tests-playwright: 
    name: 'Playwright E2E Tests'
    needs: lint-playwright
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Run e2e tests
        run: npm run test:all-chrome
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30
